
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ta_salon;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import Config.Koneksi;
/**
 *
 * @author krisl
 */
public class Login_db extends javax.swing.JFrame {
Connection conn = (Connection)Koneksi.getkoneksi();

    /**
     * Creates new form Login
     */
    public Login_db() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b_login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        t_username = new javax.swing.JTextField();
        cb_pass = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        b_reset = new javax.swing.JButton();
        t_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(226, 202, 218));
        jPanel1.setForeground(new java.awt.Color(203, 173, 173));
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 390));
        jPanel1.setLayout(null);

        b_login.setBackground(new java.awt.Color(153, 104, 104));
        b_login.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        b_login.setForeground(new java.awt.Color(255, 255, 255));
        b_login.setText("Login");
        b_login.setBorder(null);
        b_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loginActionPerformed(evt);
            }
        });
        jPanel1.add(b_login);
        b_login.setBounds(510, 280, 78, 35);

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(110, 70, 70));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 170, 90, 35);

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(110, 70, 70));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(410, 100, 90, 35);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(105, 73, 73));
        jLabel1.setText("LOGIN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(540, 30, 150, 43);

        t_username.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        t_username.setForeground(new java.awt.Color(112, 81, 81));
        t_username.setBorder(null);
        jPanel1.add(t_username);
        t_username.setBounds(522, 104, 190, 28);

        cb_pass.setBackground(new java.awt.Color(226, 202, 218));
        cb_pass.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        cb_pass.setForeground(new java.awt.Color(107, 70, 70));
        cb_pass.setText("Show Password");
        cb_pass.setAutoscrolls(true);
        cb_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_passActionPerformed(evt);
            }
        });
        jPanel1.add(cb_pass);
        cb_pass.setBounds(527, 222, 150, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ta_salon/you! (2).jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 392, 1080);

        b_reset.setBackground(new java.awt.Color(153, 104, 104));
        b_reset.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        b_reset.setForeground(new java.awt.Color(255, 255, 255));
        b_reset.setText("Reset");
        b_reset.setBorder(null);
        b_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_resetActionPerformed(evt);
            }
        });
        jPanel1.add(b_reset);
        b_reset.setBounds(620, 280, 78, 35);

        t_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        t_password.setForeground(new java.awt.Color(112, 81, 81));
        t_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(t_password);
        t_password.setBounds(520, 170, 190, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loginActionPerformed
        try {
          Statement statement = (Statement)conn.createStatement();
            ResultSet result = statement.executeQuery("select * from tb_login where " + "username = '" + t_username.getText() + "'" + "and password = '"+ t_password.getText() + "'");
            if (result.next()){
                JOptionPane.showMessageDialog(null, "Berhasil Login!", "Success", JOptionPane.INFORMATION_MESSAGE);
                new pilihan().show(); // pindah 
                dispose();
            }else if(t_username.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Username tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
                    t_username.requestFocus();
            }else if(t_password.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Password tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
                    t_password.requestFocus();
            }else{
                JOptionPane.showMessageDialog(null,"Login Gagal!","Kesalahan", JOptionPane.ERROR_MESSAGE);
                t_username.requestFocus(); 
            }   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Terjadi kesalahan "+e.getMessage());
        }
    }//GEN-LAST:event_b_loginActionPerformed

    private void cb_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_passActionPerformed
        if(cb_pass.isSelected()){
            t_password.setEchoChar((char)0);
        }else{
            t_password.setEchoChar('*');
        }
    }//GEN-LAST:event_cb_passActionPerformed

    private void b_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_resetActionPerformed
        t_username.setText("");
        t_password.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_b_resetActionPerformed

    private void t_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_db().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_login;
    private javax.swing.JButton b_reset;
    private javax.swing.JCheckBox cb_pass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JTextField t_username;
    // End of variables declaration//GEN-END:variables
}
